version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o tf.zip
      - unzip -o tf.zip -d /usr/local/bin && rm tf.zip
      - terraform -version && aws --version
  pre_build:
    commands:
      - cd terraform
      - >
        terraform init
        -backend-config="bucket=${TF_STATE_BUCKET}"
        -backend-config="key=${TF_STATE_KEY}"
        -backend-config="region=${AWS_REGION}"
        -backend-config="dynamodb_table=${TF_STATE_DDB_TABLE}"
  build:
    commands:
      - test -f plan.out || { echo "plan.out not found"; exit 1; }
      - terraform apply -auto-approve "plan.out"

